[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_program = "8Q3bQZA37hRwJ84DcrcVMp7k4LrGLjdoBGsgF6N9iEEp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'no tests'"
